name: CI
on: [push]
jobs:
  ci:
    name: Runs Javascript tests and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install, build, and test
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - run: npm install
      - run: npm run test
      - run: npm run build:chrome
      - run: npm run build:firefox
